### ISSUE TITLE
[Skizzium Launcher] Shows textbox description on button and clickable when button is invisible

### ISSUE THREAD

**Issue by timmehz** [Skizzium/Skizzium#1]
**Describe the bug**
Skizzium Launcher shows a textbox description for the unapplied changes button even if the button is invisible to the user, and the user can click the button as if it should be visible but it is not.

**To Reproduce**
1. Open Skizzium Launcher
2. go to the top of the launcher to where the downloads, notification buttons are
3. to the left of the buttons move mouse over until your mouse pointer is showing the pointer finger icon
4. wait for like 1 second till the text box description shows up

**Expected behavior**
For the textbox description to not show up and for the button to not be clickable when it is invisible to the user.

**Screenshots**
https://prnt.sc/F2Fs8N8hHQUW

**Desktop:**
 - OS: Windows 10 (Build 19045.2486)
 - Product Name: Skizzium Launcher
 - Product Version: 3.0.0-beta.2.1
 - Game Version: None

**Additional context**
None.

**Comment by uSkizzik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Shows textbox description on button and clickable when button is invisible](https://trello.com/c/AWgrkjVm/237-shows-textbox-description-on-button-and-clickable-when-button-is-invisible)

**Comment by uSkizzik** [comment]
Fixed in v3.0.0-beta.3
