### ISSUE TITLE
<skizzium> - <wont download mod and says I dont have game>

### ISSUE THREAD

**Issue by creativefiregaming** [Skizzium/Skizzium#14]
**Describe the bug**
basically I try to download the mod and it says I do not have the game, but I do infact have the game and have given it the directory.
It even shows at the menu I have the game and when I click play It works, so why would It say I don't have the game?

**To Reproduce**
1. Download mod "Fnaf WireFrame"
2. Click on 'Make sure you have sb located'
3. 

**Expected behavior**
It should let me install mod

**Screenshots**
![Screenshot 2023-12-03 110202](https://github.com/Skizzium/Skizzium/assets/152799449/e3afd4d0-38a7-4d02-aad1-a3abbd19a079)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Product Name Skizzium launcher
 - Product Version No Idea
 - Game Version: Idk

**Additional context**
please help me I just want to play Fnaf Wireframe.

**Comment by uSkizzik** [comment]
Please provide your logs. You can locate them in the settings. There's a button to upload them to a paste site, click that and send the link.
