### ISSUE TITLE
[Skizzium Launcher] - Parsing appinfo.vdf is failing, which prevents the launcher from starting up

### ISSUE THREAD

**Issue by diedyesterdaywashere** [Skizzium/Skizzium#2]
**Describe the bug**
I think title is kinda self-explanatory

**To Reproduce**
You can't really reproduce it, or atleast idk how, maybe delete vdf file?

**Expected behavior**
It should've parsed VDF and launched

**Screenshots**
https://cdn.discordapp.com/attachments/937530777736970280/1067942155823362131/app.old.log
https://cdn.discordapp.com/attachments/937530777736970280/1067942154640576562/app.log

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Product Name: Skizzium Launcher
 - Product Version: v3.0.0-beta.2.2

**Comment by uSkizzik** [comment]
Wrong version, also next time upload to hastebin

**Comment by uSkizzik** [comment]
I'll likely have to write a custom parser because the package I'm using to parse the file doesn't even have its source public anymore.

**Comment by uSkizzik** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Parsing appinfo.vdf fails because of the parser and crashes the launcher](https://trello.com/c/OMmWZz0r/301-parsing-appinfovdf-fails-because-of-the-parser-and-crashes-the-launcher)

**Comment by uSkizzik** [comment]
An update to this - Steam seems to have added some new fields to the appinfo.vdf which might be what broke the parser.  
At the moment the only work around is to open the tray menu, right click the launcher icon and select any page. This will open up the main window but will not load in your Steam games.

**Comment by uSkizzik** [comment]
Alright big thanks to @nwalkewicz who created [binary-vdf-parser](https://github.com/Skizzium/binary-vdf-parser) which I'll implement in the next update to fix the issue. I won't close this yet as I haven't implemented the new module.

**Comment by uSkizzik** [comment]
Aight this has been fixed in Skizzium Launcher 3 (Beta 3)
