### ISSUE TITLE
[Skizzium Launcher] - Launcher stuck on loading when WYD Playtest is installed

### ISSUE THREAD

**Issue by Redstone626** [Skizzium/Skizzium#3]
**Describe the bug**
the launcher won't open with WYD Playtest installed 

**To Reproduce**
open the launcher with WYD Playtest installed 
gets stuck at updating 

**Expected behavior**
it gets stuck updating 

**Desktop (please complete the following information):**
 - OS: windows 11
 - Product Name Skizzium Launcher
 - Product Version v3.0.0 beta 3

**Comment by uSkizzik** [comment]
This has been fixed in 3.0.0-beta.3.5
