### ISSUE TITLE
[Skizzium Launcher] Stuck on Checking for Updates if the game "Inside" is installed

### ISSUE THREAD

**Issue by blanana** [Skizzium/Skizzium#5]
The Launcher gets stuck on the Checking for Updates screen when opening it while the game Inside is installed.
I had Inside installed from Epic Games but it might also be a problem if it is installed from Steam.
Uninstalling Inside made it work again.

I looked through the log and found that the last instructions before it gave an error were:
Found game Inside at C:\Program Files\Epic Games\Inside
Failed to download information for game undefined:undefined:Marigold   (Marigold is Inside)
Request failed with status code 404

I assume this is because it couldn't find the assets for Inside (Error 404) which prevents it from starting.
To fix this you could try adding assets for it or making the launcher skip the game when it gets a 404 error.

**Comment by uSkizzik** [comment]
@blanana I need the full logs, the file located at `%programdata%\Skizzium Launcher\cache\epic-offers.json` and the manifest of the game. You can find the manifest in `%programdata%\Epic\EpicGamesLauncher\Data\Manifests`. You have to open every file and search for the name of the game inside.

**Comment by blanana** [comment]
[files.zip](https://github.com/Skizzium/Skizzium/files/11185599/files.zip)
Here is the Manifest and the other file. I don't have the logs anymore because they were overwritten after I got the Launcher to work and opened it a couple of times.

**Comment by uSkizzik** [comment]
> [files.zip](https://github.com/Skizzium/Skizzium/files/11185599/files.zip) Here is the Manifest and the other file. I don't have the logs anymore because they were overwritten after I got the Launcher to work and opened it a couple of times.

And is Inside detected by the launcher now? If so then the issue was likely related to the EG offers file not containing the namespace for Inside yet.

**Comment by uSkizzik** [comment]
@blanana I'll have to close this for inactivity soon.

**Comment by blanana** [comment]
Sorry, I didn't see the last message. The Launcher is now recognizing Inside after I uninstalled it and moved it to my other drive.

**Comment by uSkizzik** [comment]
Eeh I doubt the reinstalling had anything to do with it fixing itself, likely just EG changing stuff on their end.
